### PR TITLE
The first commit from #44

### PR DESCRIPTION
**Pull request by tarsius**
In #44 I said you should merge only the first commit, but you merged both. I then pointed out that you should revert the second commit and you reverted both. This new pull request allows you to merge the first commit again - and nothing else.

### CODE REVIEW

**Comment by m2ym** [comment]
Thanks. I supposed to cherry-pick the first commit very soon.

**Comment by tarsius** [comment]
I figured you were a bit busy, or something :-)

**Comment by m2ym** [comment]
Sorry. BTW, are you interested in to become a new maintainer of direx? As you said, I don't have much time to work on this project. I can transfer the repo.

**Comment by tarsius** [comment]
No, sorry. I also don't have enough time.

**Comment by m2ym** [comment]
OK. Thanks, anyway.

**Pull request merged**
